language: node_js
node_js:
  - "4.0"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm install -g gulp

script:
  - gulp
  - npm test
